In [1]:
import os

import numpy as np
import tensorflow as tf

from tensorflow_vgg import vgg16
from tensorflow_vgg import utils

## Run below cell only to create vectors of images, save the vectors in a pickle file. 

In [3]:
#data_dir = '/home/bhavyateja_potineni/homes_img'
#image_data = os.listdir(data_dir)
#with tf.Session() as sess:
#    input_ = tf.placeholder(tf.float32, [None, 224, 224, 3])
#    vgg = vgg16.Vgg16()
#    vgg.build(input_)
#success={}
#failed=[]
#for image in image_data:
#        try:
#            img = utils.load_image(os.path.join(data_dir, image))
#            img = img.reshape((1, 224, 224, 3))
#            feed_dict = {input_: img}
#            code = sess.run(vgg.relu6, feed_dict=feed_dict)
#            success[image]=code
#        except:
#            failed.append(image)
#            pass

/home/bhavyateja_potineni/image_tagging/transfer-learning/tensorflow_vgg/vgg16.npy
npy file loaded
build model started
build model finished: 0s


In [3]:
import pickle

## This cell is to write vectors in file

In [10]:
#with open('success_test_vec.pickle', 'wb') as handle:
#    pickle.dump(success, handle, protocol=pickle.HIGHEST_PROTOCOL)  

## This cell is to read vectors

In [4]:
with open('success_test_vec.pickle', 'rb') as f:
    x = pickle.load(f)

In [5]:
type(x['cdn.homes.com_cgi-bin_readimage_8a8468ba6c492f1a2667cb3d3bc395a4_1014-s-22nd-terre-haute-in-47803-4.jpg'])

numpy.ndarray

## Each image is converted into vector of size 4096

In [6]:
x['cdn.homes.com_cgi-bin_readimage_8a8468ba6c492f1a2667cb3d3bc395a4_1014-s-22nd-terre-haute-in-47803-4.jpg'].shape

(1, 4096)

In [20]:
mat=None

## convert dictionary into numpy matrix 

```
>>a = np.array([[1, 2]])
>>a
array([[1, 2]])
>>b = np.array([[5, 6]])
>>b
array([[5, 6]])
>>np.concatenate((a,b))
array([[1, 2],
       [5, 6]])
       
```
So at the end the shape of this matrix will be **(N,4096)**  *(where N is number of images)*

In [ ]:
for vec in x.values():
    if mat is None:
        mat = vec
    else:
        mat = np.concatenate((mat,vec))

In [10]:
N=10000
points = tf.constant(np.random.uniform(0, 10, (N, 2)))


In [22]:
a = np.array([[1, 2]])
a

array([[1, 2]])

In [23]:
b = np.array([[5, 6]])
b

array([[5, 6]])

In [24]:
np.concatenate((a,b))

array([[1, 2],
       [5, 6]])